# -*- coding: utf-8 -*-
"""PillaiS_CSCI1470_Prog9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11lEYf_ghSJkN8z0_zpCfJG4CUhCHgJny
"""

#***************************************************************************************************************************************************
#
# Objective: Program will open a text file with student grades and output a repot.txt file with 
#            the letter grade and average for all the exams that student took.**
#
#            **used sample text file called StudentInfo.txt file which was already created prior to program which have the following content
#              Baggins Bilbo 70 45 59
#              Gekasu Miyomi 96 97 88
#              Allen Barry 73 94 80
#              Prince Diana 88 61 36
#              Sturm Emma 90 86 45 
#
#****************************************************************************************************************************************************

#opening StudentInfo.txt
input_file = 'StudentInfo.txt'
doc = open(input_file,'r')

#making a list of each rows from StudentInfo.txt
table = doc.readlines()
doc.close()

#creating a new .txt file called report1.txt

O_file = 'report.txt'
output_file = open(O_file, 'w')

#making lists for three exams for calcualting averages for each exams
exam1 = []
exam2 = []
exam3 = []


for rows in table:
  #splitting rows to convert it in to list for ease in claculation
  row = rows.split()
  exam_average = (int(row[2])+int(row[3])+int(row[4]))/3

  #making branches for different grades
  if 90 <= exam_average:
    grade = 'A'
  elif 80 <= exam_average < 90:
    grade = 'B'
  elif 70 <= exam_average < 80:
    grade = 'C'
  elif 60 <= exam_average < 70:
    grade = 'D'
  else: grade = 'F'

  #appending all the grades for each exam to three lists
  exam1.append(int(row[2]))
  exam2.append(int(row[3]))
  exam3.append(int(row[4]))

  #adding letter grade to the list row as string and then converting the row to string
  row = row + [str(grade)]
  row = '   '.join(row)
  #writing each rows in report.txt
  output_file.write(row)
  output_file.write('\n')

#calculating average for each exams and writing it in report.txt
exam1_avg = sum(exam1)/len(exam1)
exam2_avg = sum(exam2)/len(exam2)
exam3_avg = sum(exam3)/len(exam3)
output_file.write(f'Averages: Midterm1 {exam1_avg}, Midterm2 {exam2_avg}, Final {exam3_avg}')
output_file.close()



#printing the report.txt
f = open('report.txt','r')
table = f.readlines()

for rows in table:
  row = rows.split
  print(rows)

