# -*- coding: utf-8 -*-
"""PillaiS_CSCI1470_Prog8.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PS0kT8g32vgi2VjP0lz0MmBjCFYVQYCu
"""

#**********************  Idle_8_Battle_Game.py  ************************************************************************************************
# Name: Sreerag M. Pillai
#
# Course: CSCI 1470.01
#
# Assignment: Idle programming assignment #8
#
# Algorythm: Program will ouput a battle game with deck of cards between payer 1 and 2 and outputs final score and the winner
#creating 2 lists: one list has the card names and one has the corresponding card value. 
#cardNamesPlayer1 = ["two", "three", "four", 'five', "six", 'seven', 'eight', 'nine', 'ten', "jack", "queen", "king", "ace"]
#cardValuesPlayer1 = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
#cardNamesPlayer2 = ["two", "three", "four", 'five', "six", 'seven', 'eight', 'nine', 'ten', "jack", "queen", "king", "ace"]
#cardValuesPlayer2 = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
#creating a dictionary with numbers and corresponding values
#dict1 = {}
#a=2
#for words in cardNamesPlayer1:
#  dict1[words] = a
#  a += 1
#dict2 = {}
#a=2
#for words in cardNamesPlayer2:
#  dict2[words] = a
#  a += 1
#creating a function to return values in dictionary for keys
#def value(a):
#  for b in dict1:
#    if dict1[b] == a:
#      c =str(b)
#      return c
#def value2(a):
#  for b in dict1:
#    if dict2[b] == a:
#     c = str(b)
#      return c
#p1_score = 0
#p2_score = 0
#print('Enter any key to start the game')
#user_input = input()
#while user_input != 'stop':
#  for i in range(13):
#    import random
#    num1 = random.randint(0,(len(cardValuesPlayer1)-1))
#    num2 = random.randint(0,(len(cardValuesPlayer2)-1))
#    Player1_num = num1 + 2 
#    Player2_num = num2 + 2
#    print(f'Player 1 card is {value(Player1_num)}')
#    print(f'Player 2 card is {value2(Player2_num)}')
# Removing the element from the list and printing it
#    cardNamesPlayer2.pop(num2)
#    cardNamesPlayer1.pop(num1)
#    cardValuesPlayer1.pop(num1)
#    cardValuesPlayer2.pop(num2)
#    print(f'remaing deck for player 1 {cardNamesPlayer1}')
#    print(f'remaing deck for player 1 {cardNamesPlayer2}')
# # Code to decide which player gets points for each round
#    if Player1_num > Player2_num:
#      p1_score += 1
#    elif Player2_num > Player1_num:
#      p2_score += 1
#    else: 
#      p2_score += 0
#      p1_score += 0
#    print(f'Player 1 score is {p1_score}')
#    print(f'Player 2 score is {p2_score}')
# Printing final score
#  print(f'Player 1 final score is {p1_score}')
#  print(f'Player 2 final score is {p2_score}')
# Deciding who is the final winner and printing
#  if p1_score > p2_score:
#    print('Player 1 is the winner ')
#  elif p2_score > p1_score:
#    print('Player 2 is the winner')
#  else:
#    print('Oh good game \"It is a tie \" ')
# asking user if they would like another try
#  print('would you like another try \n if you do enter key any key to start or \'stop\' to stop ')
#
#  user_input = input()
#
#****************************************************************************************************************************************************
#creating 2 lists: one list has the card names and one has the corresponding card value. 
cardNamesPlayer1 = ["two", "three", "four", 'five', "six", 'seven', 'eight', 'nine', 'ten', "jack", "queen", "king", "ace"]
cardValuesPlayer1 = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

cardNamesPlayer2 = ["two", "three", "four", 'five', "six", 'seven', 'eight', 'nine', 'ten', "jack", "queen", "king", "ace"]
cardValuesPlayer2 = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

#creating a dictionary with numbers and corresponding values
dict1 = {}
a=2
for words in cardNamesPlayer1:
  dict1[words] = a
  a += 1
dict2 = {}
a=2
for words in cardNamesPlayer2:
  dict2[words] = a
  a += 1

#creating a function to return values in dictionary for keys
def value(a):
  for b in dict1:
    if dict1[b] == a:
      c =str(b)
      return c
def value2(a):
  for b in dict1:
    if dict2[b] == a:
      c = str(b)
      return c



p1_score = 0
p2_score = 0

print('Enter any key to start the game')
user_input = input()

while user_input != 'stop':
  for i in range(13):
    import random
    num1 = random.randint(0,(len(cardValuesPlayer1)-1))
    num2 = random.randint(0,(len(cardValuesPlayer2)-1))
    Player1_num = num1 + 2 
    Player2_num = num2 + 2

    print(f'Player 1 card is {value(Player1_num)}')
    print()
    print(f'Player 2 card is {value2(Player2_num)}')
    print()
  # Removing the element from the list and printing it
    cardNamesPlayer2.pop(num2)
    cardNamesPlayer1.pop(num1)
    cardValuesPlayer1.pop(num1)
    cardValuesPlayer2.pop(num2)

    print(f'remaing deck for player 1 {cardNamesPlayer1}')
    print(f'remaing deck for player 1 {cardNamesPlayer2}')


    print()
    print()
  # Code to decide which player gets points for each round
    if Player1_num > Player2_num:
      p1_score += 1
    elif Player2_num > Player1_num:
      p2_score += 1
    else: 
      p2_score += 0
      p1_score += 0
    print(f'Player 1 score is {p1_score}')
    print(f'Player 2 score is {p2_score}')
    print()
    print()

  # Printing final score
  print()
  print()
  print(f'Player 1 final score is {p1_score}')
  print(f'Player 2 final score is {p2_score}')
  print()

  # Deciding who is the final winner and printing
  if p1_score > p2_score:
    print('Player 1 is the winner ')
  elif p2_score > p1_score:
    print('Player 2 is the winner')
  else:
    print('Oh good game \"It is a tie \" ')

  # asking user if they would like another try
  print('would you like another try \n if you do enter key any key to start or \'stop\' to stop ')

  user_input = input()





